export const API_PREFIX: string = "/api/";
export const NEXT_RANDOM_ENDPOINT = "next_random";
export const PREV_RANDOM_ENDPOINT = "prev_random";
export const FORCE_RANDOM_ENDPOINT = "force_random"
export const NEXT_ENDPOINT = "next";
export const PREV_ENDPOINT = "prev";
export const CURRENT_IMAGE_ENDPOINT = "current_image";
export const RANDOM_HISTORY_ENDPOINT = "random_history";
export const NORMAL_HISTORY_ENDPOINT = "normal_history";
export const NEXT_FOLDER_ENDPOINT = "next_folder";
export const PREV_FOLDER_ENDPOINT = "prev_folder";
export const PICK_FOLDER_ENDPOINT = "pick_folder";
export const FOLDER_HISTORY_ENDPOINT = "folder_history";
export const REINDEX_CURRENT_FOLDER_ENDPOINT = "reindex_current_folder";
export const RESET_RANDOM_HISTORY_ENDPOINT = "reset_random_history";
export const RESET_NORMAL_HISTORY_ENDPOINT = "reset_normal_history";
export const FULL_WIPE_ENDPOINT = "full_wipe";
export const STATE_ENDPOINT = "state";
